// <auto-generated />
using System;
using Fhi.Handhygiene.Dataaksess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fhi.Handhygiene.Dataaksess.Migrations
{
    [DbContext(typeof(HandhygieneContext))]
    [Migration("20250205121632_InitialPostgreSQL")]
    partial class InitialPostgreSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AvdelingKlinikk", b =>
                {
                    b.Property<int>("AvdelingerId")
                        .HasColumnType("integer");

                    b.Property<int>("KlinikkerId")
                        .HasColumnType("integer");

                    b.HasKey("AvdelingerId", "KlinikkerId");

                    b.HasIndex("KlinikkerId");

                    b.ToTable("AvdelingKlinikk");
                });

            modelBuilder.Entity("AvdelingRolle", b =>
                {
                    b.Property<int>("AvdelingerId")
                        .HasColumnType("integer");

                    b.Property<int>("RollerId")
                        .HasColumnType("integer");

                    b.HasKey("AvdelingerId", "RollerId");

                    b.HasIndex("RollerId");

                    b.ToTable("AvdelingRolle");
                });

            modelBuilder.Entity("BeskyttelsesutstyrFeilbrukType", b =>
                {
                    b.Property<int>("BeskyttelsesutstyrId")
                        .HasColumnType("integer");

                    b.Property<int>("FeilbruktyperId")
                        .HasColumnType("integer");

                    b.HasKey("BeskyttelsesutstyrId", "FeilbruktyperId");

                    b.HasIndex("FeilbruktyperId");

                    b.ToTable("BeskyttelsesutstyrFeilbrukType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Bruker.Bruker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Epost")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("ErDeaktivert")
                        .HasColumnType("boolean");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HPRNummer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdentPseudonym")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("InstitusjonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HPRNummer");

                    b.HasIndex("IdentPseudonym");

                    b.HasIndex("InstitusjonId");

                    b.ToTable("Bruker");

                    b.HasDiscriminator().HasValue("Bruker");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Bruker.ForesporselOmBrukertilgang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BehandletAvBrukerId")
                        .HasColumnType("integer");

                    b.Property<string>("BehandletAvBrukernavn")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BehandletTidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BrukerEtternavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BrukerFornavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HPRNummer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdentPseudonym")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("InstitusjonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("ForesporselOmBrukertilgang");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Aktivitet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AktivitetTypeId")
                        .HasColumnType("integer");

                    b.Property<bool?>("BenyttetHanske")
                        .HasColumnType("boolean");

                    b.Property<int>("SekunderBrukt")
                        .HasColumnType("integer");

                    b.Property<bool>("TidtakingBleUtfort")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AktivitetTypeId");

                    b.ToTable("Aktivitet");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.AktivitetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Navn");

                    b.ToTable("AktivitetType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.Beskyttelsesutstyr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BeskyttelsesutstyrObservasjonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("BleBenyttet")
                        .HasColumnType("boolean");

                    b.Property<bool>("BleBenyttetRiktig")
                        .HasColumnType("boolean");

                    b.Property<bool>("ErIndikert")
                        .HasColumnType("boolean");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("UtstyrstypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BeskyttelsesutstyrObservasjonId");

                    b.HasIndex("UtstyrstypeId");

                    b.ToTable("Beskyttelsesutstyr");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrObservasjon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BeskyttelsesutstyrSesjonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Registrerttidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RolleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SettingtypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BeskyttelsesutstyrSesjonId");

                    b.HasIndex("Opprettettidspunkt");

                    b.HasIndex("Registrerttidspunkt");

                    b.HasIndex("RolleId");

                    b.HasIndex("SettingtypeId");

                    b.ToTable("BeskyttelsesutstyrObservasjon");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Navn");

                    b.ToTable("BeskyttelsesutstyrType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Navn");

                    b.ToTable("BeskyttelsesutstyrsettingType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrType", b =>
                {
                    b.Property<int>("BeskyttelsesutstyrTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("BeskyttelsesutstyrsettingTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("ErDefaultIndikert")
                        .HasColumnType("boolean");

                    b.HasKey("BeskyttelsesutstyrTypeId", "BeskyttelsesutstyrsettingTypeId");

                    b.HasIndex("BeskyttelsesutstyrsettingTypeId");

                    b.ToTable("BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.FeilbrukType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BeskyttelsesutstyrTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BeskyttelsesutstyrTypeId");

                    b.HasIndex("Navn");

                    b.ToTable("FeilbrukType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.FireIndikasjonerObservasjon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AktivitetId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FireIndikasjonerSesjonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Registrerttidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RolleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AktivitetId");

                    b.HasIndex("FireIndikasjonerSesjonId");

                    b.HasIndex("Opprettettidspunkt");

                    b.HasIndex("Registrerttidspunkt");

                    b.HasIndex("RolleId");

                    b.ToTable("FireIndikasjonerObservasjon");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.HandsmykkeObservasjon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HandsmykkeSesjonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Registrerttidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RolleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HandsmykkeSesjonId");

                    b.HasIndex("Opprettettidspunkt");

                    b.HasIndex("Registrerttidspunkt");

                    b.HasIndex("RolleId");

                    b.ToTable("HandsmykkeObservasjon");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.HandsmykkeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ErAktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.ToTable("HandsmykkeType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Hansker.HandhygieneEtterHanskebrukType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Navn");

                    b.ToTable("HandhygieneEtterHanskebrukType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Hansker.HanskeMedIndikasjonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Navn");

                    b.ToTable("HanskeMedIndikasjonType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Hansker.HanskeObservasjon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BenyttetHanske")
                        .HasColumnType("boolean");

                    b.Property<int?>("HandhygieneEtterHanskebrukTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HanskeSesjonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Registrerttidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RolleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HandhygieneEtterHanskebrukTypeId");

                    b.HasIndex("HanskeSesjonId");

                    b.HasIndex("Opprettettidspunkt");

                    b.HasIndex("Registrerttidspunkt");

                    b.HasIndex("RolleId");

                    b.ToTable("HanskeObservasjon");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Hansker.HanskeUtenIndikasjonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Navn");

                    b.ToTable("HanskeUtenIndikasjonType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.IndikasjonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nummer")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Navn");

                    b.ToTable("IndikasjonType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Rolle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beskrivelse")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Navn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Navn");

                    b.ToTable("Rolle");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.OverforingstatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Navn");

                    b.ToTable("OverforingstatusType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.Sesjon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AvdelingId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ObservatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OverforingstatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Starttidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AvdelingId");

                    b.HasIndex("Discriminator");

                    b.HasIndex("ObservatorId");

                    b.HasIndex("Opprettettidspunkt");

                    b.HasIndex("OverforingstatusId");

                    b.HasIndex("Starttidspunkt");

                    b.ToTable("Sesjon");

                    b.HasDiscriminator().HasValue("Sesjon");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Avdeling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvdelingtypeId")
                        .HasColumnType("integer");

                    b.Property<int>("InstitusjonId")
                        .HasColumnType("integer");

                    b.Property<string>("Navn")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("AvdelingtypeId");

                    b.HasIndex("InstitusjonId");

                    b.HasIndex("Navn");

                    b.ToTable("Avdeling");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.AvdelingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Navn");

                    b.ToTable("AvdelingType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Helseforetak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("RegionaltHelseforetakId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionaltHelseforetakId");

                    b.ToTable("Helseforetak");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Institusjon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Forkortelse")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("HERId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("HelseforetakId")
                        .HasColumnType("integer");

                    b.Property<int?>("InstitusjontypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("KommuneId")
                        .HasColumnType("integer");

                    b.Property<string>("Navn")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Forkortelse");

                    b.HasIndex("HERId");

                    b.HasIndex("HelseforetakId");

                    b.HasIndex("InstitusjontypeId");

                    b.HasIndex("KommuneId");

                    b.HasIndex("Navn");

                    b.HasIndex("RegionId");

                    b.ToTable("Institusjon");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.InstitusjonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Navn");

                    b.ToTable("InstitusjonType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Klinikk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InstitusjonId")
                        .HasColumnType("integer");

                    b.Property<string>("Navn")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("InstitusjonId");

                    b.HasIndex("Navn");

                    b.ToTable("Klinikk");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Kommune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nummer")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.ToTable("Kommune");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.PredefinertKommentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstitusjonId")
                        .HasColumnType("integer");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SesjonType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstitusjonId");

                    b.ToTable("PredefinertKommentar");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Navn");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.RegionaltHelseforetak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Navn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("RegionaltHelseforetak");
                });

            modelBuilder.Entity("FireIndikasjonerObservasjonIndikasjonType", b =>
                {
                    b.Property<int>("IndikasjonstyperId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservasjonerId")
                        .HasColumnType("uuid");

                    b.HasKey("IndikasjonstyperId", "ObservasjonerId");

                    b.HasIndex("ObservasjonerId");

                    b.ToTable("FireIndikasjonerObservasjonIndikasjonType");
                });

            modelBuilder.Entity("HandsmykkeObservasjonHandsmykkeType", b =>
                {
                    b.Property<int>("HandsmykkerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservasjonerId")
                        .HasColumnType("uuid");

                    b.HasKey("HandsmykkerId", "ObservasjonerId");

                    b.HasIndex("ObservasjonerId");

                    b.ToTable("HandsmykkeObservasjonHandsmykkeType");
                });

            modelBuilder.Entity("HanskeMedIndikasjonTypeHanskeObservasjon", b =>
                {
                    b.Property<int>("HanskeMedIndikasjonTyperId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservasjonerId")
                        .HasColumnType("uuid");

                    b.HasKey("HanskeMedIndikasjonTyperId", "ObservasjonerId");

                    b.HasIndex("ObservasjonerId");

                    b.ToTable("HanskeMedIndikasjonTypeHanskeObservasjon");
                });

            modelBuilder.Entity("HanskeObservasjonHanskeUtenIndikasjonType", b =>
                {
                    b.Property<int>("HanskeUtenIndikasjonTyperId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservasjonerId")
                        .HasColumnType("uuid");

                    b.HasKey("HanskeUtenIndikasjonTyperId", "ObservasjonerId");

                    b.HasIndex("ObservasjonerId");

                    b.ToTable("HanskeObservasjonHanskeUtenIndikasjonType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Bruker.FhiAdmin", b =>
                {
                    b.HasBaseType("Fhi.Handhygiene.Domene.Bruker.Bruker");

                    b.HasDiscriminator().HasValue("FhiAdmin");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Bruker.Koordinator", b =>
                {
                    b.HasBaseType("Fhi.Handhygiene.Domene.Bruker.Bruker");

                    b.HasDiscriminator().HasValue("Koordinator");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Bruker.Observator", b =>
                {
                    b.HasBaseType("Fhi.Handhygiene.Domene.Bruker.Bruker");

                    b.HasDiscriminator().HasValue("Observator");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.BeskyttelsesutstyrSesjon", b =>
                {
                    b.HasBaseType("Fhi.Handhygiene.Domene.Sesjon.Sesjon");

                    b.HasDiscriminator().HasValue("BeskyttelsesutstyrSesjon");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.FireIndikasjonerSesjon", b =>
                {
                    b.HasBaseType("Fhi.Handhygiene.Domene.Sesjon.Sesjon");

                    b.HasDiscriminator().HasValue("FireIndikasjonerSesjon");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.HandsmykkeSesjon", b =>
                {
                    b.HasBaseType("Fhi.Handhygiene.Domene.Sesjon.Sesjon");

                    b.HasDiscriminator().HasValue("HandsmykkeSesjon");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.HanskeSesjon", b =>
                {
                    b.HasBaseType("Fhi.Handhygiene.Domene.Sesjon.Sesjon");

                    b.HasDiscriminator().HasValue("HanskeSesjon");
                });

            modelBuilder.Entity("AvdelingKlinikk", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Sted.Avdeling", null)
                        .WithMany()
                        .HasForeignKey("AvdelingerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fhi.Handhygiene.Domene.Sted.Klinikk", null)
                        .WithMany()
                        .HasForeignKey("KlinikkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AvdelingRolle", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Sted.Avdeling", null)
                        .WithMany()
                        .HasForeignKey("AvdelingerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Rolle", null)
                        .WithMany()
                        .HasForeignKey("RollerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeskyttelsesutstyrFeilbrukType", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.Beskyttelsesutstyr", null)
                        .WithMany()
                        .HasForeignKey("BeskyttelsesutstyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.FeilbrukType", null)
                        .WithMany()
                        .HasForeignKey("FeilbruktyperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Bruker.Bruker", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Sted.Institusjon", "Institusjon")
                        .WithMany("Brukere")
                        .HasForeignKey("InstitusjonId");

                    b.Navigation("Institusjon");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Aktivitet", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.AktivitetType", "AktivitetType")
                        .WithMany()
                        .HasForeignKey("AktivitetTypeId");

                    b.Navigation("AktivitetType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.Beskyttelsesutstyr", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrObservasjon", "BeskyttelsesutstyrObservasjon")
                        .WithMany("Beskyttelsesutstyrliste")
                        .HasForeignKey("BeskyttelsesutstyrObservasjonId");

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrType", "Utstyrstype")
                        .WithMany()
                        .HasForeignKey("UtstyrstypeId");

                    b.Navigation("BeskyttelsesutstyrObservasjon");

                    b.Navigation("Utstyrstype");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrObservasjon", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Sesjon.BeskyttelsesutstyrSesjon", "BeskyttelsesutstyrSesjon")
                        .WithMany("Observasjoner")
                        .HasForeignKey("BeskyttelsesutstyrSesjonId");

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Rolle", "Rolle")
                        .WithMany()
                        .HasForeignKey("RolleId");

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingType", "Settingtype")
                        .WithMany()
                        .HasForeignKey("SettingtypeId");

                    b.Navigation("BeskyttelsesutstyrSesjon");

                    b.Navigation("Rolle");

                    b.Navigation("Settingtype");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrType", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrType", "BeskyttelsesutstyrType")
                        .WithMany("BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrTyper")
                        .HasForeignKey("BeskyttelsesutstyrTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingType", "BeskyttelsesutstyrsettingType")
                        .WithMany("BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrTyper")
                        .HasForeignKey("BeskyttelsesutstyrsettingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrType_Beskyt~1");

                    b.Navigation("BeskyttelsesutstyrType");

                    b.Navigation("BeskyttelsesutstyrsettingType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.FeilbrukType", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrType", "BeskyttelsesutstyrType")
                        .WithMany("Feilbruktyper")
                        .HasForeignKey("BeskyttelsesutstyrTypeId");

                    b.Navigation("BeskyttelsesutstyrType");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.FireIndikasjonerObservasjon", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Aktivitet", "Aktivitet")
                        .WithMany()
                        .HasForeignKey("AktivitetId");

                    b.HasOne("Fhi.Handhygiene.Domene.Sesjon.FireIndikasjonerSesjon", "FireIndikasjonerSesjon")
                        .WithMany("Observasjoner")
                        .HasForeignKey("FireIndikasjonerSesjonId");

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Rolle", "Rolle")
                        .WithMany()
                        .HasForeignKey("RolleId");

                    b.Navigation("Aktivitet");

                    b.Navigation("FireIndikasjonerSesjon");

                    b.Navigation("Rolle");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.HandsmykkeObservasjon", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Sesjon.HandsmykkeSesjon", "HandsmykkeSesjon")
                        .WithMany("Observasjoner")
                        .HasForeignKey("HandsmykkeSesjonId");

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Rolle", "Rolle")
                        .WithMany()
                        .HasForeignKey("RolleId");

                    b.Navigation("HandsmykkeSesjon");

                    b.Navigation("Rolle");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Hansker.HanskeObservasjon", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Hansker.HandhygieneEtterHanskebrukType", "HandhygieneEtterHanskebrukType")
                        .WithMany()
                        .HasForeignKey("HandhygieneEtterHanskebrukTypeId");

                    b.HasOne("Fhi.Handhygiene.Domene.Sesjon.HanskeSesjon", "HanskeSesjon")
                        .WithMany("Observasjoner")
                        .HasForeignKey("HanskeSesjonId");

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Rolle", "Rolle")
                        .WithMany()
                        .HasForeignKey("RolleId");

                    b.Navigation("HandhygieneEtterHanskebrukType");

                    b.Navigation("HanskeSesjon");

                    b.Navigation("Rolle");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.Sesjon", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Sted.Avdeling", "Avdeling")
                        .WithMany("Sesjoner")
                        .HasForeignKey("AvdelingId");

                    b.HasOne("Fhi.Handhygiene.Domene.Bruker.Observator", "Observator")
                        .WithMany()
                        .HasForeignKey("ObservatorId");

                    b.HasOne("Fhi.Handhygiene.Domene.Sesjon.OverforingstatusType", "Overforingstatus")
                        .WithMany("Sesjoner")
                        .HasForeignKey("OverforingstatusId");

                    b.Navigation("Avdeling");

                    b.Navigation("Observator");

                    b.Navigation("Overforingstatus");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Avdeling", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Sted.AvdelingType", "Avdelingtype")
                        .WithMany()
                        .HasForeignKey("AvdelingtypeId");

                    b.HasOne("Fhi.Handhygiene.Domene.Sted.Institusjon", "Institusjon")
                        .WithMany("Avdelinger")
                        .HasForeignKey("InstitusjonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avdelingtype");

                    b.Navigation("Institusjon");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Helseforetak", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Sted.RegionaltHelseforetak", "RegionaltHelseforetak")
                        .WithMany()
                        .HasForeignKey("RegionaltHelseforetakId");

                    b.Navigation("RegionaltHelseforetak");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Institusjon", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Sted.Helseforetak", "Helseforetak")
                        .WithMany()
                        .HasForeignKey("HelseforetakId");

                    b.HasOne("Fhi.Handhygiene.Domene.Sted.InstitusjonType", "Institusjontype")
                        .WithMany()
                        .HasForeignKey("InstitusjontypeId");

                    b.HasOne("Fhi.Handhygiene.Domene.Sted.Kommune", "Kommune")
                        .WithMany()
                        .HasForeignKey("KommuneId");

                    b.HasOne("Fhi.Handhygiene.Domene.Sted.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.Navigation("Helseforetak");

                    b.Navigation("Institusjontype");

                    b.Navigation("Kommune");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Klinikk", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Sted.Institusjon", "Institusjon")
                        .WithMany("Klinikker")
                        .HasForeignKey("InstitusjonId");

                    b.Navigation("Institusjon");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.PredefinertKommentar", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Sted.Institusjon", null)
                        .WithMany("PredefinerteKommmentarer")
                        .HasForeignKey("InstitusjonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FireIndikasjonerObservasjonIndikasjonType", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.IndikasjonType", null)
                        .WithMany()
                        .HasForeignKey("IndikasjonstyperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.FireIndikasjonerObservasjon", null)
                        .WithMany()
                        .HasForeignKey("ObservasjonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HandsmykkeObservasjonHandsmykkeType", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.HandsmykkeType", null)
                        .WithMany()
                        .HasForeignKey("HandsmykkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.HandsmykkeObservasjon", null)
                        .WithMany()
                        .HasForeignKey("ObservasjonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HanskeMedIndikasjonTypeHanskeObservasjon", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Hansker.HanskeMedIndikasjonType", null)
                        .WithMany()
                        .HasForeignKey("HanskeMedIndikasjonTyperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Hansker.HanskeObservasjon", null)
                        .WithMany()
                        .HasForeignKey("ObservasjonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HanskeObservasjonHanskeUtenIndikasjonType", b =>
                {
                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Hansker.HanskeUtenIndikasjonType", null)
                        .WithMany()
                        .HasForeignKey("HanskeUtenIndikasjonTyperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fhi.Handhygiene.Domene.Observasjon.Hansker.HanskeObservasjon", null)
                        .WithMany()
                        .HasForeignKey("ObservasjonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrObservasjon", b =>
                {
                    b.Navigation("Beskyttelsesutstyrliste");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrType", b =>
                {
                    b.Navigation("BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrTyper");

                    b.Navigation("Feilbruktyper");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingType", b =>
                {
                    b.Navigation("BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrTyper");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.OverforingstatusType", b =>
                {
                    b.Navigation("Sesjoner");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Avdeling", b =>
                {
                    b.Navigation("Sesjoner");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sted.Institusjon", b =>
                {
                    b.Navigation("Avdelinger");

                    b.Navigation("Brukere");

                    b.Navigation("Klinikker");

                    b.Navigation("PredefinerteKommmentarer");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.BeskyttelsesutstyrSesjon", b =>
                {
                    b.Navigation("Observasjoner");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.FireIndikasjonerSesjon", b =>
                {
                    b.Navigation("Observasjoner");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.HandsmykkeSesjon", b =>
                {
                    b.Navigation("Observasjoner");
                });

            modelBuilder.Entity("Fhi.Handhygiene.Domene.Sesjon.HanskeSesjon", b =>
                {
                    b.Navigation("Observasjoner");
                });
#pragma warning restore 612, 618
        }
    }
}
