//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export abstract class AktivitetTypeKonstanter
{
	public static Desinfeksjon: string = `DESINFEKSJON`;
	public static Handvask: string = `HANDVASK`;
	public static IkkeUtfort: string = `IKKE_UTFORT`;
	public static IkkeRegistrert: string = `IKKE_REGISTRERT`;
}
