//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Rolle } from './Rolle';
import { AvdelingType } from './AvdelingType';

export interface Avdeling
{
	id: number;
	institusjonId: number;
	avdelingTypeId: number;
	navn: string;
	roller: Rolle[];
	avdelingType: AvdelingType;
}
