//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { BeskyttelsesutstyrType } from './BeskyttelsesutstyrType';

export interface BeskyttelsesutstyrsettingType
{
	id: number;
	kode: string;
	navn: string;
	utstyrstyper: BeskyttelsesutstyrType[];
}
