//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class BeskyttelsesutstyrTypeKonstanter
{
	public static Hansker: string = `HANSKER`;
	public static Smittefrakk: string = `SMITTEFRAKK`;
	public static Munnbind: string = `MUNNBIND`;
	public static Oyebeskyttelse: string = `OYEBESKYTTELSE`;
	public static Andedrettsvern: string = `ANDEDRETTSVERN`;
	public static Hette: string = `HETTE`;
	public static Plastforkle: string = `PLASTFORKLE`;
	public static Stellefrakk: string = `STELLEFRAKK`;
}
