//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { BeskyttelsesutstyrType } from './BeskyttelsesutstyrType';
import { FeilbrukType } from './FeilbrukType';

export interface Beskyttelsesutstyr
{
	id: number;
	bleBenyttet: boolean;
	erIndikert: boolean;
	utstyrstype: BeskyttelsesutstyrType;
	feilbruktyper: FeilbrukType[];
	bleBenyttetRiktig: boolean;
	kommentar: string;
}
