//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface BeskyttelsesutstyrOversiktRapport
{
	utstyrsnavn: string;
	feilbruktyper: string[];
	bleBenyttet: boolean;
	bleBenyttetRiktig: boolean;
	erIndikert: boolean;
	kommentar: string;
}
