//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class BeskyttelsesutstyrsettingTypeKonstanter
{
	public static BasaleSmittevernrutiner: string = `BASALE_SMITTEVERNRUTINER`;
	public static Kontaktsmitte: string = `KONTAKTSMITTE`;
	public static Drapesmitte: string = `DRAPESMITTE`;
	public static Luftsmitte: string = `LUFTSMITTE`;
}
