//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Observasjon } from './Observasjon';
import { IndikasjonType } from './IndikasjonType';
import { Aktivitet } from './Aktivitet';

export interface FireIndikasjonerObservasjon extends Observasjon
{
	indikasjonstyper?: IndikasjonType[];
	aktivitet?: Aktivitet;
}
