//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class HanskeUtenIndikasjonTypeKonstanter
{
	public static StellUtenKroppvaesker: string = `STELL_UTEN_KROPPVAESKER`;
	public static Mat: string = `MAT`;
	public static Annet: string = `Annet`;
}
