//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class HanskeMedIndikasjonTypeKonstanter
{
	public static Kroppvaesker: string = `KROPPVAESKER`;
	public static Smitte: string = `SMITTE`;
	public static Annet: string = `Annet`;
}
