//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { AvdelingOversiktRapport } from './AvdelingOversiktRapport';

export interface InstitusjonOversiktRapport
{
	id: number;
	navn: string;
	antallSesjoner: number;
	antallObservasjoner: number;
	avdelinger: AvdelingOversiktRapport[];
}
