//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InstitusjonType } from './InstitusjonType';
import { Region } from './Region';
import { Kommune } from './Kommune';
import { Helseforetak } from './Helseforetak';

export interface InstitusjonRapport
{
	id: number;
	navn: string;
	forkortelse: string;
	herId: string;
	institusjontype: InstitusjonType;
	region: Region;
	kommune: Kommune;
	helseforetak: Helseforetak;
}
