//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InstitusjonRapport } from './InstitusjonRapport';

export interface KoordinatorForHelseforetak
{
	opprettettidspunkt: any;
	fornavn: string;
	etternavn: string;
	epost: string;
	identPseudonym: string;
	erDeaktivert: boolean;
	hprNummer: string;
	institusjoner: InstitusjonRapport[];
	endretIdentPseudonym?: string;
	endretHPRNummer?: string;
}
