//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Rolle } from './Rolle';

export interface OppdaterAvdelingRequest
{
	id: number;
	navn: string;
	avdelingTypeId: number;
	roller: Rolle[];
}
