//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Avdeling } from './Avdeling';

export interface Sesjon<TObservasjon>
{
	id: string;
	avdeling: Avdeling;
	starttidspunkt: Date;
	observasjoner?: TObservasjon[];
	institusjonsnavn?: string;
	institusjonId?: number;
	kommentar?: string;
}
