//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum SesjonType {
	FireIndikasjoner = 1,
	InnUt = 2,
	Handsmykker = 3,
	Hansker = 4,
	Beskyttelsesutstyr = 5,
	IkkeValgt = 6
}
