services:

  fhi.handhygiene.admin:
    image: ${DOCKER_REGISTRY-}fhihandhygieneadmin
    build:
      context: .
      dockerfile: Fhi.Handhygiene.Admin/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080 # Add ;https://+:8443 for https support
      - ConnectionStrings__HandhygieneConnection=Server=database; Database=HandHygiene; Username=handhygiene; Password=SomeB4DSecur1ty; SSLMode=disable
    ports:
     - 8081:8080

  fhi.handhygiene.observasjon:
    image: ${DOCKER_REGISTRY-}fhihandhygieneobservasjon
    build:
      context: .
      dockerfile: Fhi.Handhygiene.Observasjon/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080 # Add ;https://+:8443 for https support
      - ConnectionStrings__HandhygieneConnection=Server=database; Database=HandHygiene; Username=handhygiene; Password=SomeB4DSecur1ty; SSLMode=disable
    ports:
     - 8080:8080

  database:
    image: postgres:17.2
    environment:
      POSTGRES_DB: HandHygiene
      POSTGRES_USER: handhygiene
      POSTGRES_PASSWORD: SomeB4DSecur1ty 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
     - 5432:5432

volumes:
  db-data:
