# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectAdmin: 'Fhi.Handhygiene.Admin'
  projectObservasjon: 'Fhi.Handhygiene.Observasjon'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseNode@1
  displayName: "Bruk Node 18.x"
  inputs:
    version: '18.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=FileSystem  /p:SkipInvalidConfigurations=true /p:PublishBaseUrl="$(build.artifactstagingdirectory)\\"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: OctopusPack@4
  inputs:
    PackageId: '$(projectAdmin)'
    PackageFormat: 'NuPkg'
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(projectAdmin)'
    OutputPath: '$(Build.ArtifactStagingDirectory)/QA/$(projectAdmin).Octopack'
    NuGetAuthor: 'FHI'
    NuGetTitle: '$(projectAdmin)'
    NuGetDescription: 'Håndhygiene: Admin-grensesnitt'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/$(projectAdmin)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Test/$(projectAdmin).zip'
    replaceExistingArchive: true

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/$(projectAdmin)'
    Contents: '**/*'
    RemoveSourceFolder: true

- task: OctopusPack@4
  inputs:
    PackageId: '$(projectObservasjon)'
    PackageFormat: 'NuPkg'
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(projectObservasjon)'
    OutputPath: '$(Build.ArtifactStagingDirectory)/QA/$(projectObservasjon).Octopack'
    NuGetAuthor: 'FHI'
    NuGetTitle: '$(projectObservasjon)'
    NuGetDescription: 'Håndhygiene: Observasjon-grensesnitt'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/$(projectObservasjon)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Test/$(projectObservasjon).zip'
    replaceExistingArchive: true

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/$(projectObservasjon)'
    Contents: '**/*'
    RemoveSourceFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\'
    ArtifactName: 'drop'
    publishLocation: 'Container'