//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { AktivitetType } from './AktivitetType';

export interface Aktivitet
{
	aktivitetType: AktivitetType;
	sekunderBrukt?: number;
	tidtakingBleUtfort: boolean;
	benyttetHanske?: boolean;
}
