//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { FeilbrukType } from './FeilbrukType';

export interface BeskyttelsesutstyrType
{
	id: number;
	kode: string;
	navn: string;
	erDefaultIndikert: boolean;
	erIndikert: boolean;
	feilbruktyper: FeilbrukType[];
}
