//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Bruker
{
	id: number;
	institusjonId: number;
	opprettettidspunkt: any;
	fornavn: string;
	etternavn: string;
	epost: string;
	identPseudonym: string;
	erDeaktivert: boolean;
	hprNummer: string;
}
