//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { FireIndikasjonerObservasjon } from './FireIndikasjonerObservasjon';
import { Sesjon } from './Sesjon';

export interface FireIndikasjonerSesjon extends Sesjon<FireIndikasjonerObservasjon>
{
}
