//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ForesporselOmBrukertilgang
{
	id: number;
	institusjonId?: number;
	brukerFornavn: string;
	brukerEtternavn: string;
	identPseudonym: string;
	hprNummer: string;
	status: number;
	opprettettidspunkt: any;
	godkjenttidspunkt: any;
}
