//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class HandhygieneEtterHanskebrukTypeKonstanter
{
	public static Ja: string = `JA`;
	public static Nei: string = `NEI`;
	public static IkkeIndikert: string = `IKKE_INDIKERT`;
}
