//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface HandsmykkeType
{
	id: number;
	kode: string;
	navn: string;
}
