//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export abstract class HandsmykkeTypeKonstanter
{
	public static AltOk: string = `ALT_OK`;
	public static Ring: string = `RING`;
	public static KlokkeArmband: string = `KLOKKE_ARMBAND`;
	public static LangNegl: string = `LANG_NEGL`;
	public static KunstigNeglShellac: string = `KUNSTIG_NEGL_SHELLAC`;
	public static Kortermet: string = `KORTERMET`;
	public static Langermet: string = `LANGERMET`;
}
