//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Observasjon } from './Observasjon';
import { HanskeMedIndikasjonType } from './HanskeMedIndikasjonType';
import { HanskeUtenIndikasjonType } from './HanskeUtenIndikasjonType';
import { HandhygieneEtterHanskebrukType } from './HandhygieneEtterHanskebrukType';

export interface HanskeObservasjon extends Observasjon
{
	hanskeMedIndikasjonTyper?: HanskeMedIndikasjonType[];
	hanskeUtenIndikasjonTyper?: HanskeUtenIndikasjonType[];
	benyttetHanske: boolean;
	handhygieneEtterHanskebrukType?: HandhygieneEtterHanskebrukType;
}
