//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { RegionaltHelseforetak } from './RegionaltHelseforetak';

export interface Helseforetak
{
	id: number;
	navn: string;
	regionaltHelseforetakId: number;
	regionaltHelseforetak: RegionaltHelseforetak;
}
