//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export abstract class IndikasjonTypeKonstanter
{
	public static FoerPasient: string = `FOER_PASIENT`;
	public static AseptiskeProsedyrer: string = `ASEPTISKE_PROSEDYRER`;
	public static Kroppsveske: string = `KROPPSVESKE`;
	public static EtterPasient: string = `ETTER_PASIENT`;
}
