//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface InnloggetBruker
{
	id: string;
	identPseudonym: string;
	navn: string;
	erKoordinator: boolean;
	erFhiAdmin: boolean;
	erObservator: boolean;
	institusjonsIder: number[];
	fornavn: string;
	etternavn: string;
	hprNummer: string;
}
