//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Avdeling } from './Avdeling';
import { InstitusjonType } from './InstitusjonType';
import { Region } from './Region';
import { Kommune } from './Kommune';
import { Helseforetak } from './Helseforetak';

export interface Institusjon
{
	id: number;
	navn: string;
	forkortelse: string;
	herId: string;
	avdelinger: Avdeling[];
	institusjontype: InstitusjonType;
	region: Region;
	kommune: Kommune;
	harObservasjoner: boolean;
	helseforetak: Helseforetak;
}
