//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Rolle } from './Rolle';
import { IndikasjonType } from './IndikasjonType';
import { Aktivitet } from './Aktivitet';
import { HandsmykkeType } from './HandsmykkeType';
import { BeskyttelsesutstyrOversiktRapport } from './BeskyttelsesutstyrOversiktRapport';
import { HanskeObservasjon } from './HanskeObservasjon';
import { BeskyttelsesutstyrObservasjon } from './BeskyttelsesutstyrObservasjon';

export interface ObservasjonOversiktRapport
{
	id: any;
	rolle: Rolle;
	kommentar: string;
	registrerttidspunkt: any;
	indikasjonstyper: IndikasjonType[];
	aktivitet: Aktivitet;
	handsmykketyper: HandsmykkeType[];
	beskyttelsesutstyrsetting: string;
	beskyttelsesutstyr: BeskyttelsesutstyrOversiktRapport[];
	hanskeObservasjon: HanskeObservasjon;
	beskyttelsesutstyrObservasjon: BeskyttelsesutstyrObservasjon;
}
