//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Rolle } from './Rolle';

export interface Observasjon
{
	id: string;
	rolle: Rolle;
	registrerttidspunkt?: Date;
	sesjonId: string;
	kommentar?: string;
}
