//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface OpprettInstitusjonRequest
{
	institusjonsnavn: string;
	forkortelse: string;
	herId: string;
	institusjonTypeId: number;
	koordinatorHPRnummer: string;
	koordinatorPseudonym: string;
	koordinatorFornavn: string;
	koordinatorEtternavn: string;
	koordinatorEpost: string;
	regionId: number;
	kommuneId: number;
	helseforetakId: number;
}
