//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class OverforingstatusTypeKonstanter
{
	public static OverfortTilFhi: string = `OVERFORT_TIL_FHI`;
	public static OverfortTilKoordinator: string = `OVERFORT_TIL_KOORDINATOR`;
}
