//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Avdeling } from './Avdeling';
import { ObservasjonOversiktRapport } from './ObservasjonOversiktRapport';

export interface SesjonOversiktRapport
{
	id: any;
	type: string;
	observatorNavn: string;
	avdeling: Avdeling;
	starttidspunkt: any;
	opprettettidspunkt: any;
	kommentar: string;
	overforingstatus: any;
	observasjoner: ObservasjonOversiktRapport[];
	erValgt: boolean;
}
