export class Urls {
  static LoginsideUrl = '';
  static StartsideForObservasjonUrl = 'registrering';
  static RegistrereFireIndikasjonerUrl = 'registrering/fire-indikasjoner';
  static RegistrereHandsmykkerUrl = 'registrering/handsmykker';
  static RegistrereHanskeUrl = 'registrering/hanske';
  static RegistrereBeskyttelsesutstyrUrl = 'registrering/beskyttelsesutstyr';
  static IkkeSendteSesjonerUrl = 'sesjoner/ikke-sendte';
  static SendteSesjonerUrl = 'sesjoner/sendte';
  static FireIndikasjonerSesjonUrl = 'sesjoner/fire-indikasjoner';
  static HandsmykkeSesjonUrl = 'sesjoner/handsmykker';
  static HanskeSesjonUrl = 'sesjoner/hanske';
  static BeskyttelsesutstyrSesjonUrl = 'sesjoner/beskyttelsesutstyr';
  static SendteFireIndikasjonerSesjonUrl = 'sesjoner/sendte/fire-indikasjoner';
  static SendteHandsmykkeSesjonUrl = 'sesjoner/sendte/handsmykker';
  static SendteHanskeSesjonUrl = 'sesjoner/sendte/hanske';
  static SendteBeskyttelsesutstyrSesjonUrl = 'sesjoner/sendte/beskyttelsesutstyr';
  static ProfilUrl = 'profil';
}
