export class UrlPaths {
  static forside = 'forside';
  static observasjoner = 'fhiadmin/observasjoner';
  static observasjonerAvdeling = 'fhiadmin/observasjoner/avdeling';
  static overforSesjoner = 'koordinator/overforing';
  static redigeringAvInstitusjoner = 'fhiadmin/institusjoner';
  static redigeringAvKodeverk = 'fhiadmin/kodeverk';
  static redigeringAvHandsmykketyper = 'fhiadmin/handsmykketyper';
  static redigeringAvAvdelinger = 'koordinator/avdelinger';
  static redigeringAvKlinikker = 'koordinator/klinikker';
  static redigeringAvKoordinatorer = 'koordinator/koordinatorer';
  static redigeringAvObservatorer = 'koordinator/observatorer';
  static redigeringAvPredefinertkommentarer = 'koordinator/predefinertkommentarer';
  static profil = 'profil';
  static byttInstitusjon = 'byttinstitusjon';
  static institusjoner = 'fhiadmin/institusjoner';
  static fhiAdminOversikt = 'fhiadmin/oversikt';
  static foresporsel = 'koordinator/foresporsel';
  static helseforetak = 'fhiadmin/helseforetak';
  static epost = 'fhiadmin/epost';
  static rapporter = 'koordinator/rapporter';
  static fireindikasjonerEtterlevelse = 'fireindikasjoner/etterlevelse';
  static fireindikasjonerEtterlevelsePdf = 'fireindikasjoner/etterlevelse-fire-indikasjoner-pdf';
  static handsmykkerEtterlevelsePdf = 'handsmykker/etterlevelse-handsmykker-pdf';
  static nedlastingExcel = 'faste-rapporter/avdelingsrapport';
}
